<?php /** @var $block \HimaMage\OrderSuccessPage\Block\Details */ ?>
<?php foreach ($block->getTotals() as $code => $total): ?>
    <?php if ($total->getBlockName()): ?>
        <?php echo $block->getChildHtml($total->getBlockName(), false); ?>
    <?php else:?>
        <tr class="<?php /* @escapeNotVerified */ echo $code?>">
            <th colspan="5" <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?> scope="row">
                <?php if ($total->getStrong()):?>
                    <strong><?php echo $block->escapeHtml($total->getLabel());?></strong>
                <?php else:?>
                    <?php echo $block->escapeHtml($total->getLabel());?>
                <?php endif?>
            </th>
            <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?> data-th="<?php echo $block->escapeHtml($total->getLabel());?>">
                <?php if ($total->getStrong()):?>
                    <strong><?php /* @escapeNotVerified */ echo $block->formatValue($total) ?></strong>
                <?php else:?>
                    <?php /* @escapeNotVerified */ echo $block->formatValue($total) ?>
                <?php endif?>
            </td>
        </tr>
    <?php endif?>
<?php endforeach?>
